version: 2
project_name: murailobot

before:
  hooks:
    - go mod tidy
    - go mod download
    - go generate ./...
    - go vet ./...
    - golangci-lint run
    - go test ./...

builds:
  - id: "{{ .ProjectName }}-amd64"
    main: .
    binary: "{{ .ProjectName }}"
    env:
      - CGO_ENABLED=1
    goos:
      - linux
    goarch:
      - amd64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
      - -X main.builtBy=goreleaser
  - id: "{{ .ProjectName }}-arm64"
    main: .
    binary: "{{ .ProjectName }}"
    env:
      - CGO_ENABLED=1
      - CC=aarch64-linux-gnu-gcc
    goos:
      - linux
    goarch:
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
      - -X main.builtBy=goreleaser

archives:
  - name_template: "{{ .ProjectName }}-v{{ .Version }}-{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    wrap_in_directory: true
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README.md

checksum:
  name_template: "{{ .ProjectName }}-v{{ .Version }}_checksums.txt"
  algorithm: sha256

dockers:
  - use: buildx
    goos: linux
    goarch: amd64
    ids:
      - "{{ .ProjectName }}-amd64"
    dockerfile: Dockerfile.amd64
    image_templates:
      - ghcr.io/edgard/{{ .ProjectName }}:v{{ .Version }}-amd64
    build_flag_templates:
      - --pull
      - --platform=linux/amd64
      - --label=org.opencontainers.image.created={{ .Date }}
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.description={{ .ProjectName }} {{ .Version }} {{ .Date }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.source=https://github.com/edgard/{{ .ProjectName }}
      - --label=org.opencontainers.image.url=https://github.com/edgard/{{ .ProjectName }}
      - --label=org.opencontainers.image.licenses=MIT
      - --label=org.opencontainers.image.vendor=edgard
      - --label=org.opencontainers.image.base.name=debian:bullseye-slim

  - use: buildx
    goos: linux
    goarch: arm64
    ids:
      - "{{ .ProjectName }}-arm64"
    dockerfile: Dockerfile.arm64
    image_templates:
      - ghcr.io/edgard/{{ .ProjectName }}:v{{ .Version }}-arm64
    build_flag_templates:
      - --pull
      - --platform=linux/arm64
      - --label=org.opencontainers.image.created={{ .Date }}
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.description={{ .ProjectName }} {{ .Version }} {{ .Date }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.source=https://github.com/edgard/{{ .ProjectName }}
      - --label=org.opencontainers.image.url=https://github.com/edgard/{{ .ProjectName }}
      - --label=org.opencontainers.image.licenses=MIT
      - --label=org.opencontainers.image.vendor=edgard
      - --label=org.opencontainers.image.base.name=arm64v8/debian:bullseye-slim

docker_manifests:
  - name_template: ghcr.io/edgard/{{ .ProjectName }}:v{{ .Version }}
    image_templates:
      - ghcr.io/edgard/{{ .ProjectName }}:v{{ .Version }}-amd64
      - ghcr.io/edgard/{{ .ProjectName }}:v{{ .Version }}-arm64

  - name_template: ghcr.io/edgard/{{ .ProjectName }}:v{{ .Major }}
    image_templates:
      - ghcr.io/edgard/{{ .ProjectName }}:v{{ .Version }}-amd64
      - ghcr.io/edgard/{{ .ProjectName }}:v{{ .Version }}-arm64

  - name_template: ghcr.io/edgard/{{ .ProjectName }}:v{{ .Major }}.{{ .Minor }}
    image_templates:
      - ghcr.io/edgard/{{ .ProjectName }}:v{{ .Version }}-amd64
      - ghcr.io/edgard/{{ .ProjectName }}:v{{ .Version }}-arm64

  - name_template: ghcr.io/edgard/{{ .ProjectName }}:latest
    image_templates:
      - ghcr.io/edgard/{{ .ProjectName }}:v{{ .Version }}-amd64
      - ghcr.io/edgard/{{ .ProjectName }}:v{{ .Version }}-arm64

release:
  github:
    owner: edgard
    name: "{{ .ProjectName }}"
  draft: false
  prerelease: auto
  discussion_category_name: Releases

changelog:
  sort: asc
  use: github
  groups:
    - title: Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: Bug fixes
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: Others
      order: 999
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - Merge pull request
      - Merge branch
