project_name: murailobot

before:
  hooks:
    - go mod tidy
    - go mod download

builds:
  - main: ./cmd/murailobot
    binary: murailobot
    env:
      - GO111MODULE=on
    goos:
      - linux
    goarch:
      - amd64

archives:
  - name_template: "{{ .ProjectName }}-{{ .Version }}.{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    wrap_in_directory: true
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE

dockers:
  - use: buildx
    goos: linux
    goarch: amd64
    image_templates:
      - ghcr.io/edgard/{{ .ProjectName }}:{{ .Tag }}
      - ghcr.io/edgard/{{ .ProjectName }}:{{ .Major }}
      - ghcr.io/edgard/{{ .ProjectName }}:{{ .Major }}.{{ .Minor }}
      - ghcr.io/edgard/{{ .ProjectName }}:latest
    build_flag_templates:
      - --pull
      - --label=org.opencontainers.image.created={{ .Date }}
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.source=https://github.com/edgard/{{ .ProjectName }}
      - --label=org.opencontainers.image.url=https://github.com/edgard/{{ .ProjectName }}

checksum:
  name_template: "sha256sums.txt"
  algorithm: sha256

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - Merge pull request
      - Merge branch

snapshot:
  name_template: "{{ incpatch .Version }}-SNAPSHOT"
