version: 2
project_name: murailobot

# Skip building binaries, we only want Docker images
builds:
  - skip: true

env:
  - GO111MODULE=on
  - CGO_ENABLED=1

# Docker image configurations for each platform
dockers:
  - use: buildx
    goos: linux
    goarch: amd64
    dockerfile: Dockerfile
    image_templates:
      - ghcr.io/edgard/{{ .ProjectName }}:{{ .Version }}-amd64
    build_flag_templates:
      - --pull
      - --platform=linux/amd64
      - --build-arg=VERSION={{.Version}}
      - --build-arg=COMMIT={{.ShortCommit}}
      - --build-arg=DATE={{.Date}}
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.description={{ .ProjectName }} {{ .Version }} {{ .Date }}
      - --label=org.opencontainers.image.created={{ .Date }}
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.ref.name={{ .Version }}-amd64
      - --label=org.opencontainers.image.source=https://github.com/edgard/{{ .ProjectName }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
      - --label=org.opencontainers.image.url=https://github.com/edgard/{{ .ProjectName }}
      - --label=org.opencontainers.image.documentation=https://github.com/edgard/{{ .ProjectName }}/blob/main/README.md
      - --label=org.opencontainers.image.issues=https://github.com/edgard/{{ .ProjectName }}/issues
      - --label=org.opencontainers.image.vendor=edgard
      - --label=org.opencontainers.image.authors=edgard
      - --label=org.opencontainers.image.licenses=CC0-1.0
      - --label=org.opencontainers.image.base.name=alpine:3.21
      - --label=org.opencontainers.image.registry=ghcr.io
      - --label=com.github.package.type=container
      - --label=com.github.package.vcs-ref={{ .FullCommit }}
      - --annotation=org.opencontainers.image.title="{{ .ProjectName }}"
      - --annotation=org.opencontainers.image.description="{{ .ProjectName }} {{ .Version }} {{ .Date }}"
      - --annotation=org.opencontainers.image.created="{{ .Date }}"
      - --annotation=org.opencontainers.image.version="{{ .Version }}"
      - --annotation=org.opencontainers.image.ref.name="{{ .Version }}-amd64"
      - --annotation=org.opencontainers.image.source="https://github.com/edgard/{{ .ProjectName }}"
      - --annotation=org.opencontainers.image.revision="{{ .FullCommit }}"
      - --annotation=org.opencontainers.image.url="https://github.com/edgard/{{ .ProjectName }}"
      - --annotation=org.opencontainers.image.documentation="https://github.com/edgard/{{ .ProjectName }}/blob/main/README.md"
      - --annotation=org.opencontainers.image.issues="https://github.com/edgard/{{ .ProjectName }}/issues"
      - --annotation=org.opencontainers.image.vendor="edgard"
      - --annotation=org.opencontainers.image.authors="edgard"
      - --annotation=org.opencontainers.image.licenses="CC0-1.0"
      - --annotation=org.opencontainers.image.base.name="alpine:3.21"
      - --annotation=org.opencontainers.image.registry="ghcr.io"
      - --annotation=com.github.package.type="container"
      - --annotation=com.github.package.vcs-ref="{{ .FullCommit }}"

  - use: buildx
    goos: linux
    goarch: arm64
    dockerfile: Dockerfile
    image_templates:
      - ghcr.io/edgard/{{ .ProjectName }}:{{ .Version }}-arm64
    build_flag_templates:
      - --pull
      - --platform=linux/arm64
      - --build-arg=VERSION={{.Version}}
      - --build-arg=COMMIT={{.ShortCommit}}
      - --build-arg=DATE={{.Date}}
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.description={{ .ProjectName }} {{ .Version }} {{ .Date }}
      - --label=org.opencontainers.image.created={{ .Date }}
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.ref.name={{ .Version }}-arm64
      - --label=org.opencontainers.image.source=https://github.com/edgard/{{ .ProjectName }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
      - --label=org.opencontainers.image.url=https://github.com/edgard/{{ .ProjectName }}
      - --label=org.opencontainers.image.documentation=https://github.com/edgard/{{ .ProjectName }}/blob/main/README.md
      - --label=org.opencontainers.image.issues=https://github.com/edgard/{{ .ProjectName }}/issues
      - --label=org.opencontainers.image.vendor=edgard
      - --label=org.opencontainers.image.authors=edgard
      - --label=org.opencontainers.image.licenses=CC0-1.0
      - --label=org.opencontainers.image.base.name=alpine:3.21
      - --label=org.opencontainers.image.registry=ghcr.io
      - --label=com.github.package.type=container
      - --label=com.github.package.vcs-ref={{ .FullCommit }}
      - --annotation=org.opencontainers.image.title="{{ .ProjectName }}"
      - --annotation=org.opencontainers.image.description="{{ .ProjectName }} {{ .Version }} {{ .Date }}"
      - --annotation=org.opencontainers.image.created="{{ .Date }}"
      - --annotation=org.opencontainers.image.version="{{ .Version }}"
      - --annotation=org.opencontainers.image.ref.name="{{ .Version }}-arm64"
      - --annotation=org.opencontainers.image.source="https://github.com/edgard/{{ .ProjectName }}"
      - --annotation=org.opencontainers.image.revision="{{ .FullCommit }}"
      - --annotation=org.opencontainers.image.url="https://github.com/edgard/{{ .ProjectName }}"
      - --annotation=org.opencontainers.image.documentation="https://github.com/edgard/{{ .ProjectName }}/blob/main/README.md"
      - --annotation=org.opencontainers.image.issues="https://github.com/edgard/{{ .ProjectName }}/issues"
      - --annotation=org.opencontainers.image.vendor="edgard"
      - --annotation=org.opencontainers.image.authors="edgard"
      - --annotation=org.opencontainers.image.licenses="CC0-1.0"
      - --annotation=org.opencontainers.image.base.name="alpine:3.21"
      - --annotation=org.opencontainers.image.registry="ghcr.io"
      - --annotation=com.github.package.type="container"
      - --annotation=com.github.package.vcs-ref="{{ .FullCommit }}"

# Multi-platform manifest configurations
docker_manifests:
  - name_template: ghcr.io/edgard/{{ .ProjectName }}:{{ .Version }}
    image_templates:
      - ghcr.io/edgard/{{ .ProjectName }}:{{ .Version }}-amd64
      - ghcr.io/edgard/{{ .ProjectName }}:{{ .Version }}-arm64

  - name_template: ghcr.io/edgard/{{ .ProjectName }}:{{ .Major }}
    image_templates:
      - ghcr.io/edgard/{{ .ProjectName }}:{{ .Version }}-amd64
      - ghcr.io/edgard/{{ .ProjectName }}:{{ .Version }}-arm64

  - name_template: ghcr.io/edgard/{{ .ProjectName }}:{{ .Major }}.{{ .Minor }}
    image_templates:
      - ghcr.io/edgard/{{ .ProjectName }}:{{ .Version }}-amd64
      - ghcr.io/edgard/{{ .ProjectName }}:{{ .Version }}-arm64

  - name_template: ghcr.io/edgard/{{ .ProjectName }}:latest
    image_templates:
      - ghcr.io/edgard/{{ .ProjectName }}:{{ .Version }}-amd64
      - ghcr.io/edgard/{{ .ProjectName }}:{{ .Version }}-arm64

release:
  github:
    owner: edgard
    name: "{{ .ProjectName }}"
  draft: false
  prerelease: auto
  header: |
    ## {{ .ProjectName }} {{ .Version }} ({{ .Date }})

    This release was automatically generated by GitHub Actions.

changelog:
  sort: asc
  use: github
  groups:
    - title: Breaking Changes
      regexp: "^.*?(feat|fix|build|chore|ci|docs|style|refactor|perf|test)(\\([[:word:]]+\\))?!:.+$"
      order: 0
    - title: Features
      regexp: "^.*?feat(\\([[:word:]]+\\))?:.+$"
      order: 1
    - title: Bug Fixes
      regexp: "^.*?fix(\\([[:word:]]+\\))?:.+$"
      order: 2
    - title: Performance Improvements
      regexp: "^.*?perf(\\([[:word:]]+\\))?:.+$"
      order: 3
    - title: Refactoring
      regexp: "^.*?refactor(\\([[:word:]]+\\))?:.+$"
      order: 4
    - title: Code Style
      regexp: "^.*?style(\\([[:word:]]+\\))?:.+$"
      order: 5
    - title: Documentation
      regexp: "^.*?docs(\\([[:word:]]+\\))?:.+$"
      order: 6
    - title: Tests
      regexp: "^.*?test(\\([[:word:]]+\\))?:.+$"
      order: 7
    - title: Build System
      regexp: "^.*?build(\\([[:word:]]+\\))?:.+$"
      order: 8
    - title: CI
      regexp: "^.*?ci(\\([[:word:]]+\\))?:.+$"
      order: 9
    - title: Chores
      regexp: "^.*?chore(\\([[:word:]]+\\))?:.+$"
      order: 10
    - title: Reverts
      regexp: "^.*?revert(\\([[:word:]]+\\))?:.+$"
      order: 11
    - title: Others
      order: 999
  filters:
    exclude:
      - "^Merge pull request"
      - "^Merge branch"
      - "^Merge remote"
