version: 2
project_name: murailobot

before:
  hooks:
    - go mod tidy
    - go mod download
    - go generate ./...
    - go vet ./...
    - golangci-lint run
    - go test ./...

builds:
  - id: amd64
    main: .
    binary: murailobot
    env:
      - CGO_ENABLED=1
    goos:
      - linux
    goarch:
      - amd64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
      - -X main.builtBy=goreleaser
  - id: arm64
    main: .
    binary: murailobot
    env:
      - CGO_ENABLED=1
      - CC=aarch64-linux-gnu-gcc
    goos:
      - linux
    goarch:
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
      - -X main.builtBy=goreleaser

archives:
  - name_template: "{{ .ProjectName }}-{{ .Version }}.{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    wrap_in_directory: true
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README.md

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

dockers:
  - use: buildx
    goos: linux
    goarch: amd64
    ids:
      - amd64
      - arm64
    dockerfile: Dockerfile
    image_templates:
      - ghcr.io/edgard/{{ .ProjectName }}:{{ .Tag }}
      - ghcr.io/edgard/{{ .ProjectName }}:{{ .Major }}
      - ghcr.io/edgard/{{ .ProjectName }}:{{ .Major }}.{{ .Minor }}
      - ghcr.io/edgard/{{ .ProjectName }}:latest
    build_flag_templates:
      - --pull
      - --platform=linux/amd64,linux/arm64
      - --label=org.opencontainers.image.created={{ .Date }}
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.description={{ .ProjectName }} {{ .Version }} {{ .Date }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.source=https://github.com/edgard/{{ .ProjectName }}
      - --label=org.opencontainers.image.url=https://github.com/edgard/{{ .ProjectName }}
      - --label=org.opencontainers.image.licenses=MIT
      - --label=org.opencontainers.image.vendor=edgard
      - --label=org.opencontainers.image.base.name=scratch
      - --annotation=index:org.opencontainers.image.created="{{ .Date }}"
      - --annotation=index:org.opencontainers.image.title="{{ .ProjectName }}"
      - --annotation=index:org.opencontainers.image.description="{{ .ProjectName }} {{ .Version }} {{ .Date }}"
      - --annotation=index:org.opencontainers.image.revision="{{ .FullCommit }}"
      - --annotation=index:org.opencontainers.image.version="{{ .Version }}"
      - --annotation=index:org.opencontainers.image.source="https://github.com/edgard/{{ .ProjectName }}"
      - --annotation=index:org.opencontainers.image.url="https://github.com/edgard/{{ .ProjectName }}"
      - --annotation=index:org.opencontainers.image.licenses="MIT"
      - --annotation=index:org.opencontainers.image.vendor="edgard"
      - --annotation=index:org.opencontainers.image.base.name="scratch"

release:
  github:
    owner: edgard
    name: murailobot
  draft: false
  prerelease: auto
  discussion_category_name: Releases

changelog:
  sort: asc
  use: github
  groups:
    - title: Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: Bug fixes
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: Others
      order: 999
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - Merge pull request
      - Merge branch
