FROM --platform=linux/amd64 debian:bullseye-slim

RUN apt-get update && apt-get install -y \
    libsqlite3-0 \
    ca-certificates \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

# GoReleaser will copy the pre-built binary
COPY murailobot /app/murailobot

ENTRYPOINT ["/app/murailobot"]
